In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer,KNNImputer

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [9]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [11]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [13]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [15]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=18)

In [21]:
x_train

      Age  Pclass     Fare
464   NaN       3   8.0500
871  47.0       1  52.5542
506  33.0       2  26.0000
147   9.0       3  34.3750
488  30.0       3   8.0500
..    ...     ...      ...
702  18.0       3  14.4542
837   NaN       3   8.0500
120  21.0       2  73.5000
275  63.0       1  77.9583
298   NaN       1  30.5000

[712 rows x 3 columns]

In [23]:
knn =KNNImputer()
x_train_trf=knn.fit_transform(x_train)
x_test_trf=knn.transform(x_test)

In [33]:
lr = LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred=lr.predict(x_test_trf)
accuracy_score(y_test,y_pred)

0.770949720670391