In [51]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/sanke/Downloads/cars.csv")

In [7]:
df.sample(5)

        brand  km_driven    fuel         owner  selling_price
3910  Hyundai      58609  Petrol  Second Owner         195000
3320     Ford      80000  Diesel   First Owner         300000
2120   Maruti     120000  Diesel   Third Owner         215000
756   Hyundai      80000  Petrol  Second Owner          50000
5932  Renault      80000  Diesel   First Owner         450000

In [13]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

# 1.Onehot encoding in pandas

In [17]:
pd.get_dummies(df,columns=['fuel','owner']) # It can use only for Data anlysis purpose

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# 2.K-1 onehotencoding

with the help of this first column has been removed from dataset category

In [21]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True) # It is used for not arising multicardinality problem

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# 3.One Hot Encoding in Machine Learning

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [31]:
x_train

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner
...        ...        ...     ...           ...
3606      Ford      35000  Diesel   First Owner
5704    Maruti     120000  Petrol   First Owner
6637      Tata      15000  Petrol   First Owner
2575    Maruti      32500  Diesel  Second Owner
7336     Isuzu     121000  Diesel   First Owner

[6502 rows x 4 columns]

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [57]:
ohe = OneHotEncoder(drop='first', sparse_output=False,dtype=np.int32) # drop is used to avoid multicolinearity
                    # dtype is use to convert datatype  
# sparse value is false bacuse ans has been in sparse matrix format

In [45]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']])
x_test_new=ohe.transform(x_test[['fuel','owner']])

In [49]:
x_train_new.shape

(6502, 7)

In [53]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))
# hstack is used to merge the 'brand' and 'km_driven' column with x_train_new dataset

array([['Hyundai', 35000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Jeep', 60000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 25000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Tata', 15000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 32500, 1.0, ..., 1.0, 0.0, 0.0],
       ['Isuzu', 121000, 1.0, ..., 0.0, 0.0, 0.0]], dtype=object)

# 4.OneHotEncoding for multiple categories

In [67]:
counts = df['brand'].value_counts

In [69]:
counts

<bound method IndexOpsMixin.value_counts of 0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...
8123    Hyundai
8124    Hyundai
8125     Maruti
8126       Tata
8127       Tata
Name: brand, Length: 8128, dtype: object>

In [71]:
df['brand'].nunique()
threshold = 100

In [75]:
rep = counts[counts <= threshold].index

TypeError: '<=' not supported between instances of 'method' and 'int'